# Kubernetes'e diyoruz ki: "Sana vereceğim bu tarif v1 (version 1) kurallarına uyuyor."
apiVersion: v1 

# Ne oluşturmak istiyoruz? Bir Namespace.
kind: Namespace 

metadata:
  # Bu namespace'in adı 'test' olsun. 
  # Neden kullanıyoruz?: Geliştirme ve deneme aşamasındaki uygulamalarımız 
  # burada çalışacak. Bozulursa üzülmeyeceğimiz kum havuzumuz burası.
  name: test 

---
# Üç tire (---) işareti, aynı dosya içinde ikinci bir kaynağa geçtiğimizi belirtir.
# Yani iki farklı dosyaya bölmek yerine tek dosyada işi bitiriyoruz.

apiVersion: v1
kind: Namespace
metadata:
  # Bu namespace'in adı 'production' olsun.
  # Neden kullanıyoruz?: Müşteriye/Kullanıcıya açık, canlı ortamımız burası. 
  # Testleri geçen sağlam uygulamalar buraya gelecek.
  name: production

