apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: test
type: Opaque
data:
  mysql-root-password: ..
  mysql-password: ...

---
apiVersion: v1
kind: PersistentVolumeClaim 
metadata:
  name: mysql-pv-claim
  namespace: test
spec:
  accessModes:
    - ReadWriteOnce # Sadece tek bir node tarafından okuma/yazma modunda bağlanabilir
  resources:
    requests:
      # Neden PVC kullanıyoruz?: Pod silinirse veya çökerse veritabanımızdaki veriler uçmasın diye 
      # cluster'dan 2 Gigabaytlık kalıcı, sağlam bir disk alanı talep ediyoruz.
      storage: 2Gi 

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wp-pv-claim
  namespace: test
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      # WordPress'e yüklenen resimler, temalar kaybolmasın diye ona da alan ayırıyoruz.
      storage: 2Gi

---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: production
type: Opaque
data:
  mysql-root-password: ...
  mysql-password: ...

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  namespace: production
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi # Canlı ortam olduğu için diski biraz daha büyük tuttuk.

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wp-pv-claim
  namespace: production
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
