name: K8s Yerel CI-CD

on:
  push:
    branches:
      - main

jobs:
  altyapiyi_guncelle:
    runs-on: self-hosted
    steps:
      - name: Repoyu Klonla
        uses: actions/checkout@v4

      - name: Ansible ile K8s Kurulumunu Tetikle
        run: |
          echo "Ansible playbook basliyor..."
          cd infrastructure/ansible
          ansible-playbook k8s-kurulum.yml
